analytics:
  twitter: null
  google: UA-74172259-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
title: HΛКłM CΛLLłER
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.75
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#68f900'
    - '#1d1cfe'
    - '#ff0d01'
    - '#63e7fe'
    - '#fc7b5b'
  lightness: 0.5
purpose: []
favicon: null
name: hakimcallier
typography_spectrum: 0.30315
