name: hakimcallier
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11822
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Hakim Callier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74172259-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6afb01'
    - '#1e1bff'
    - '#08b90a'
    - '#ff0e01'
    - '#fd7e5f'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
