name: hakimcallier
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17408
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'i make music, art and things to watch.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74172259-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68f900'
    - '#1d1cfe'
    - '#ff0d01'
    - '#63e7fe'
    - '#fc7b5b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
