title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.5430108
  lightness: 0
  brandColors:
    - '#6BFB02'
    - '#2931FC'
    - '#FC0E03'
    - '#1E331E'
    - '#63EBFB'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74172259-1
  facebook: null
favicon: null
name: hakimcallier
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.08243728
layout_spectrum: 1
