title: 'music {{ art }} style'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.75
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#68f900'
    - '#1d1cfe'
    - '#ff0d01'
    - '#63e7fe'
    - '#fc7b5b'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74172259-1
  facebook: null
name: hakim callier
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2060932
layout_spectrum: 1
