title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.125
  brandStrength: 0.6630824
  lightness: 0
  brandColors:
    - '#FF071C'
    - '#401560'
    - '#44D0E9'
    - '#025C9C'
    - '#FEFDD6'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74172259-1
  facebook: null
favicon: null
name: hakimcallier
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9301075
layout_spectrum: 1
